# Main workflow for testing and releasing

name: CI/CD

env:
  GOVERSION: "1.22.4"
  NAME: "sav2json"
  PREFIX: "sav2json-${{  github.ref_name }}"

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install zip gzip tar

    - name: Build linux
      run: GOOS=linux GOARCH=amd64 go build -o ./build/linux/ ./cmd/sav2json

    - name: Package linux
      run: tar --directory=build/linux -czvf ${{ env.PREFIX }}-linux-amd64.tar.gz sav2json

    - name: Build windows
      run: GOOS=windows GOARCH=amd64 go build -o ./build/windows/ ./cmd/sav2json

    - name: Package windows
      run: zip -j ${{ env.PREFIX }}-windows-amd64.zip ./build/windows/sav2json.exe

    - name: Build darwin
      run: GOOS=darwin GOARCH=amd64 go build -o ./build/darwin/ ./cmd/sav2json

    - name: Package darwin
      run: zip -j ${{ env.PREFIX }}-darwin-amd64.zip ./build/darwin/sav2json

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        files: |
          ${{ env.PREFIX }}-darwin-amd64.zip
          ${{ env.PREFIX }}-linux-amd64.tar.gz
          ${{ env.PREFIX }}-windows-amd64.zip
